version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d:cached
    ports:
      - 5432:5432
    environment:
      - POSTGRES_NAME=pretest_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -p 5432

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8008:8008"
    environment:
      - POSTGRES_NAME=pretest_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    command: sh run_web.sh
    depends_on:
      - db
